name: calculator_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  math_expressions: ^2.6.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  test: ^1.25.14

flutter:
  uses-material-design: true
